apiVersion: apps/v1

kind: Deployment

metadata:
  name: golang-server

spec:
  replicas: 1

  selector:
    matchLabels:
      app: golang-server
      tier: golang

  template:
    metadata:
      labels:
        app: golang-server
        tier: golang

    spec:
      containers:
      - name: desafio-k8s

        image: alleycarvalho/desafio-k8s

        ports:
        - containerPort: 8000
