steps:

- id: "Compilando a aplicação"
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'greeting']
  env: ['GOPATH=.']

- id: "Rodando testes..."
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v', './...']
  env: ['GOPATH=.']

- id: "Criando build da imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafio-k8s', '.']

images:
  - 'gcr.io/$PROJECT_ID/desafio-k8s'
